---
- hosts: webservers
  become: yes
  connection: ssh
  user: ansible


  tasks:
    - name: creating multiple users
      user: name='{{item}}' state=absent
      with_items:
        - Raj
        - Hari
        - Sai
        - Pavan
        - Rahul
